#
# This file is part of Dragonfly.
# (c) Copyright 2007, 2008 by Christo Butcher
# Licensed under the LGPL.
#
#   Dragonfly is free software: you can redistribute it and/or modify it
#   under the terms of the GNU Lesser General Public License as published
#   by the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   Dragonfly is distributed in the hope that it will be useful, but
#   WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#   Lesser General Public License for more details.
#
#   You should have received a copy of the GNU Lesser General Public
#   License along with Dragonfly.  If not, see
#   <http://www.gnu.org/licenses/>.
#

"""
    This file builds the mapping from key-name to Typeable instances.
"""


import win32con
from dragonfly.actions.keyboard import keyboard, Typeable


#---------------------------------------------------------------------------
# Mapping of name -> typeable.

typeables = {
    # Lowercase letter keys
    "a":                keyboard.get_typeable(char='a'),
    "alpha":            keyboard.get_typeable(char='a'),
    "b":                keyboard.get_typeable(char='b'),
    "bravo":            keyboard.get_typeable(char='b'),
    "c":                keyboard.get_typeable(char='c'),
    "charlie":          keyboard.get_typeable(char='c'),
    "d":                keyboard.get_typeable(char='d'),
    "delta":            keyboard.get_typeable(char='d'),
    "e":                keyboard.get_typeable(char='e'),
    "echo":             keyboard.get_typeable(char='e'),
    "f":                keyboard.get_typeable(char='f'),
    "foxtrot":          keyboard.get_typeable(char='f'),
    "g":                keyboard.get_typeable(char='g'),
    "golf":             keyboard.get_typeable(char='g'),
    "h":                keyboard.get_typeable(char='h'),
    "hotel":            keyboard.get_typeable(char='h'),
    "i":                keyboard.get_typeable(char='i'),
    "india":            keyboard.get_typeable(char='i'),
    "j":                keyboard.get_typeable(char='j'),
    "juliet":           keyboard.get_typeable(char='j'),
    "k":                keyboard.get_typeable(char='k'),
    "kilo":             keyboard.get_typeable(char='k'),
    "l":                keyboard.get_typeable(char='l'),
    "lima":             keyboard.get_typeable(char='l'),
    "m":                keyboard.get_typeable(char='m'),
    "mike":             keyboard.get_typeable(char='m'),
    "n":                keyboard.get_typeable(char='n'),
    "november":         keyboard.get_typeable(char='n'),
    "o":                keyboard.get_typeable(char='o'),
    "oscar":            keyboard.get_typeable(char='o'),
    "p":                keyboard.get_typeable(char='p'),
    "papa":             keyboard.get_typeable(char='p'),
    "q":                keyboard.get_typeable(char='q'),
    "quebec":           keyboard.get_typeable(char='q'),
    "r":                keyboard.get_typeable(char='r'),
    "romeo":            keyboard.get_typeable(char='r'),
    "s":                keyboard.get_typeable(char='s'),
    "sierra":           keyboard.get_typeable(char='s'),
    "t":                keyboard.get_typeable(char='t'),
    "tango":            keyboard.get_typeable(char='t'),
    "u":                keyboard.get_typeable(char='u'),
    "uniform":          keyboard.get_typeable(char='u'),
    "v":                keyboard.get_typeable(char='v'),
    "victor":           keyboard.get_typeable(char='v'),
    "w":                keyboard.get_typeable(char='w'),
    "whisky":           keyboard.get_typeable(char='w'),
    "x":                keyboard.get_typeable(char='x'),
    "xray":             keyboard.get_typeable(char='x'),
    "y":                keyboard.get_typeable(char='y'),
    "yankee":           keyboard.get_typeable(char='y'),
    "z":                keyboard.get_typeable(char='z'),
    "zulu":             keyboard.get_typeable(char='z'),

    # Uppercase letter keys
    "A":                keyboard.get_typeable(char='A'),
    "Alpha":            keyboard.get_typeable(char='A'),
    "B":                keyboard.get_typeable(char='B'),
    "Bravo":            keyboard.get_typeable(char='B'),
    "C":                keyboard.get_typeable(char='C'),
    "Charlie":          keyboard.get_typeable(char='C'),
    "D":                keyboard.get_typeable(char='D'),
    "Delta":            keyboard.get_typeable(char='D'),
    "E":                keyboard.get_typeable(char='E'),
    "Echo":             keyboard.get_typeable(char='E'),
    "F":                keyboard.get_typeable(char='F'),
    "Foxtrot":          keyboard.get_typeable(char='F'),
    "G":                keyboard.get_typeable(char='G'),
    "Golf":             keyboard.get_typeable(char='G'),
    "H":                keyboard.get_typeable(char='H'),
    "Hotel":            keyboard.get_typeable(char='H'),
    "I":                keyboard.get_typeable(char='I'),
    "India":            keyboard.get_typeable(char='I'),
    "J":                keyboard.get_typeable(char='J'),
    "Juliet":           keyboard.get_typeable(char='J'),
    "K":                keyboard.get_typeable(char='K'),
    "Kilo":             keyboard.get_typeable(char='K'),
    "L":                keyboard.get_typeable(char='L'),
    "Lima":             keyboard.get_typeable(char='L'),
    "M":                keyboard.get_typeable(char='M'),
    "Mike":             keyboard.get_typeable(char='M'),
    "N":                keyboard.get_typeable(char='N'),
    "November":         keyboard.get_typeable(char='N'),
    "O":                keyboard.get_typeable(char='O'),
    "Oscar":            keyboard.get_typeable(char='O'),
    "P":                keyboard.get_typeable(char='P'),
    "Papa":             keyboard.get_typeable(char='P'),
    "Q":                keyboard.get_typeable(char='Q'),
    "Quebec":           keyboard.get_typeable(char='Q'),
    "R":                keyboard.get_typeable(char='R'),
    "Romeo":            keyboard.get_typeable(char='R'),
    "S":                keyboard.get_typeable(char='S'),
    "Sierra":           keyboard.get_typeable(char='S'),
    "T":                keyboard.get_typeable(char='T'),
    "Tango":            keyboard.get_typeable(char='T'),
    "U":                keyboard.get_typeable(char='U'),
    "Uniform":          keyboard.get_typeable(char='U'),
    "V":                keyboard.get_typeable(char='V'),
    "Victor":           keyboard.get_typeable(char='V'),
    "W":                keyboard.get_typeable(char='W'),
    "Whisky":           keyboard.get_typeable(char='W'),
    "X":                keyboard.get_typeable(char='X'),
    "Xray":             keyboard.get_typeable(char='X'),
    "Y":                keyboard.get_typeable(char='Y'),
    "Yankee":           keyboard.get_typeable(char='Y'),
    "Z":                keyboard.get_typeable(char='Z'),
    "Zulu":             keyboard.get_typeable(char='Z'),

    # Number keys
    "0":                keyboard.get_typeable(char='0'),
    "zero":             keyboard.get_typeable(char='0'),
    "1":                keyboard.get_typeable(char='1'),
    "one":              keyboard.get_typeable(char='1'),
    "2":                keyboard.get_typeable(char='2'),
    "two":              keyboard.get_typeable(char='2'),
    "3":                keyboard.get_typeable(char='3'),
    "three":            keyboard.get_typeable(char='3'),
    "4":                keyboard.get_typeable(char='4'),
    "four":             keyboard.get_typeable(char='4'),
    "5":                keyboard.get_typeable(char='5'),
    "five":             keyboard.get_typeable(char='5'),
    "6":                keyboard.get_typeable(char='6'),
    "six":              keyboard.get_typeable(char='6'),
    "7":                keyboard.get_typeable(char='7'),
    "seven":            keyboard.get_typeable(char='7'),
    "8":                keyboard.get_typeable(char='8'),
    "eight":            keyboard.get_typeable(char='8'),
    "9":                keyboard.get_typeable(char='9'),
    "nine":             keyboard.get_typeable(char='9'),

    # Symbol keys
    "bang":             keyboard.get_typeable(char='!'),
    "exclamation":      keyboard.get_typeable(char='!'),
    "at":               keyboard.get_typeable(char='@'),
    "hash":             keyboard.get_typeable(char='#'),
    "dollar":           keyboard.get_typeable(char='$'),
    "percent":          keyboard.get_typeable(char='%'),
    "caret":            keyboard.get_typeable(char='^'),
    "and":              keyboard.get_typeable(char='&'),
    "ampersand":        keyboard.get_typeable(char='&'),
    "star":             keyboard.get_typeable(char='*'),
    "asterisk":         keyboard.get_typeable(char='*'),
    "leftparen":        keyboard.get_typeable(char='('),
    "lparen":           keyboard.get_typeable(char='('),
    "rightparen":       keyboard.get_typeable(char=')'),
    "rparen":           keyboard.get_typeable(char=')'),
    "minus":            keyboard.get_typeable(char='-'),
    "hyphen":           keyboard.get_typeable(char='-'),
    "underscore":       keyboard.get_typeable(char='_'),
    "plus":             keyboard.get_typeable(char='+'),
    "backtick":         keyboard.get_typeable(char='`'),
    "tilde":            keyboard.get_typeable(char='~'),
    "leftbracket":      keyboard.get_typeable(char='['),
    "lbracket":         keyboard.get_typeable(char='['),
    "rightbracket":     keyboard.get_typeable(char=']'),
    "rbracket":         keyboard.get_typeable(char=']'),
    "leftbrace":        keyboard.get_typeable(char='{'),
    "lbrace":           keyboard.get_typeable(char='{'),
    "rightbrace":       keyboard.get_typeable(char='}'),
    "rbrace":           keyboard.get_typeable(char='}'),
    "backslash":        keyboard.get_typeable(char='\\'),
    "bar":              keyboard.get_typeable(char='|'),
    "colon":            keyboard.get_typeable(char=':'),
    "semicolon":        keyboard.get_typeable(char=';'),
    "apostrophe":       keyboard.get_typeable(char="'"),
    "singlequote":      keyboard.get_typeable(char="'"),
    "squote":           keyboard.get_typeable(char="'"),
    "quote":            keyboard.get_typeable(char='"'),
    "doublequote":      keyboard.get_typeable(char='"'),
    "dquote":           keyboard.get_typeable(char='"'),
    "comma":            keyboard.get_typeable(char=','),
    "dot":              keyboard.get_typeable(char='.'),
    "slash":            keyboard.get_typeable(char='/'),
    "lessthan":         keyboard.get_typeable(char='<'),
    "leftangle":        keyboard.get_typeable(char='<'),
    "langle":           keyboard.get_typeable(char='<'),
    "greaterthan":      keyboard.get_typeable(char='>'),
    "rightangle":       keyboard.get_typeable(char='>'),
    "rangle":           keyboard.get_typeable(char='>'),
    "question":         keyboard.get_typeable(char='?'),
    "equal":            keyboard.get_typeable(char='='),
    "equals":           keyboard.get_typeable(char='='),

    # Whitespace and editing keys
    "enter":            Typeable(code=win32con.VK_RETURN, name='enter'),
    "tab":              Typeable(code=win32con.VK_TAB, name='tab'),
    "space":            Typeable(code=win32con.VK_SPACE, name='space'),
    "backspace":        Typeable(code=win32con.VK_BACK, name='backspace'),
    "delete":           Typeable(code=win32con.VK_DELETE, name='delete'),
    "del":              Typeable(code=win32con.VK_DELETE, name='del'),

    # Modifier keys
    "shift":            Typeable(code=win32con.VK_SHIFT, name='shift'),
    "control":          Typeable(code=win32con.VK_CONTROL, name='control'),
    "ctrl":             Typeable(code=win32con.VK_CONTROL, name='ctrl'),
    "alt":              Typeable(code=win32con.VK_MENU, name='alt'),
    "altgr":            Typeable(code=win32con.VK_RMENU, name='altgr'),
    "rcontrol":         Typeable(code=win32con.VK_RCONTROL, name='rcontrol'),
    "capital":          Typeable(code=win32con.VK_CAPITAL, name='capital'),

    # Special keys
    "escape":           Typeable(code=win32con.VK_ESCAPE, name='escape'),
    "insert":           Typeable(code=win32con.VK_INSERT, name='insert'),
    "pause":            Typeable(code=win32con.VK_PAUSE, name='pause'),
    "win":              Typeable(code=win32con.VK_LWIN, name='win'),
    "apps":             Typeable(code=win32con.VK_APPS, name='apps'),
    "popup":            Typeable(code=win32con.VK_APPS, name='popup'),

    # Navigation keys
    "up":               Typeable(code=win32con.VK_UP, name='up'),
    "down":             Typeable(code=win32con.VK_DOWN, name='down'),
    "left":             Typeable(code=win32con.VK_LEFT, name='left'),
    "right":            Typeable(code=win32con.VK_RIGHT, name='right'),
    "pageup":           Typeable(code=win32con.VK_PRIOR, name='pageup'),
    "pgup":             Typeable(code=win32con.VK_PRIOR, name='pgup'),
    "pagedown":         Typeable(code=win32con.VK_NEXT, name='pagedown'),
    "pgdown":           Typeable(code=win32con.VK_NEXT, name='pgdown'),
    "home":             Typeable(code=win32con.VK_HOME, name='home'),
    "end":              Typeable(code=win32con.VK_END, name='end'),

    # Number pad keys
    "npmul":            Typeable(code=win32con.VK_MULTIPLY, name='npmul'),
    "npadd":            Typeable(code=win32con.VK_ADD, name='npadd'),
    "npsep":            Typeable(code=win32con.VK_SEPARATOR, name='npsep'),
    "npsub":            Typeable(code=win32con.VK_SUBTRACT, name='npsub'),
    "npdec":            Typeable(code=win32con.VK_DECIMAL, name='npdec'),
    "npdiv":            Typeable(code=win32con.VK_DIVIDE, name='npdiv'),
    "numpad0":          Typeable(code=win32con.VK_NUMPAD0, name='numpad0'),
    "np0":              Typeable(code=win32con.VK_NUMPAD0, name='np0'),
    "numpad1":          Typeable(code=win32con.VK_NUMPAD1, name='numpad1'),
    "np1":              Typeable(code=win32con.VK_NUMPAD1, name='np1'),
    "numpad2":          Typeable(code=win32con.VK_NUMPAD2, name='numpad2'),
    "np2":              Typeable(code=win32con.VK_NUMPAD2, name='np2'),
    "numpad3":          Typeable(code=win32con.VK_NUMPAD3, name='numpad3'),
    "np3":              Typeable(code=win32con.VK_NUMPAD3, name='np3'),
    "numpad4":          Typeable(code=win32con.VK_NUMPAD4, name='numpad4'),
    "np4":              Typeable(code=win32con.VK_NUMPAD4, name='np4'),
    "numpad5":          Typeable(code=win32con.VK_NUMPAD5, name='numpad5'),
    "np5":              Typeable(code=win32con.VK_NUMPAD5, name='np5'),
    "numpad6":          Typeable(code=win32con.VK_NUMPAD6, name='numpad6'),
    "np6":              Typeable(code=win32con.VK_NUMPAD6, name='np6'),
    "numpad7":          Typeable(code=win32con.VK_NUMPAD7, name='numpad7'),
    "np7":              Typeable(code=win32con.VK_NUMPAD7, name='np7'),
    "numpad8":          Typeable(code=win32con.VK_NUMPAD8, name='numpad8'),
    "np8":              Typeable(code=win32con.VK_NUMPAD8, name='np8'),
    "numpad9":          Typeable(code=win32con.VK_NUMPAD9, name='numpad9'),
    "np9":              Typeable(code=win32con.VK_NUMPAD9, name='np9'),

    # Function keys
    "f1":               Typeable(code=win32con.VK_F1, name='f1'),
    "f2":               Typeable(code=win32con.VK_F2, name='f2'),
    "f3":               Typeable(code=win32con.VK_F3, name='f3'),
    "f4":               Typeable(code=win32con.VK_F4, name='f4'),
    "f5":               Typeable(code=win32con.VK_F5, name='f5'),
    "f6":               Typeable(code=win32con.VK_F6, name='f6'),
    "f7":               Typeable(code=win32con.VK_F7, name='f7'),
    "f8":               Typeable(code=win32con.VK_F8, name='f8'),
    "f9":               Typeable(code=win32con.VK_F9, name='f9'),
    "f10":              Typeable(code=win32con.VK_F10, name='f10'),
    "f11":              Typeable(code=win32con.VK_F11, name='f11'),
    "f12":              Typeable(code=win32con.VK_F12, name='f12'),
    "f13":              Typeable(code=win32con.VK_F13, name='f13'),
    "f14":              Typeable(code=win32con.VK_F14, name='f14'),
    "f15":              Typeable(code=win32con.VK_F15, name='f15'),
    "f16":              Typeable(code=win32con.VK_F16, name='f16'),
    "f17":              Typeable(code=win32con.VK_F17, name='f17'),
    "f18":              Typeable(code=win32con.VK_F18, name='f18'),
    "f19":              Typeable(code=win32con.VK_F19, name='f19'),
    "f20":              Typeable(code=win32con.VK_F20, name='f20'),
    "f21":              Typeable(code=win32con.VK_F21, name='f21'),
    "f22":              Typeable(code=win32con.VK_F22, name='f22'),
    "f23":              Typeable(code=win32con.VK_F23, name='f23'),
    "f24":              Typeable(code=win32con.VK_F24, name='f24'),

    # Multimedia keys
    "volumeup":         Typeable(code=win32con.VK_VOLUME_UP, name='volumeup'),
    "volup":            Typeable(code=win32con.VK_VOLUME_UP, name='volup'),
    "volumedown":       Typeable(code=win32con.VK_VOLUME_DOWN, name='volumedown'),
    "voldown":          Typeable(code=win32con.VK_VOLUME_DOWN, name='voldown'),
    "volumemute":       Typeable(code=win32con.VK_VOLUME_MUTE, name='volumemute'),
    "volmute":          Typeable(code=win32con.VK_VOLUME_MUTE, name='volmute'),
    "tracknext":        Typeable(code=win32con.VK_MEDIA_NEXT_TRACK, name='tracknext'),
    "trackprev":        Typeable(code=win32con.VK_MEDIA_PREV_TRACK, name='trackprev'),
    "playpause":        Typeable(code=win32con.VK_MEDIA_PLAY_PAUSE, name='playpause'),
    "browserback":      Typeable(code=win32con.VK_BROWSER_BACK, name='browserback'),
    "browserforward":   Typeable(code=win32con.VK_BROWSER_FORWARD, name='browserforward'),

    # list of virtual keys codes : https://msdn.microsoft.com/fr-fr/library/windows/desktop/dd375731(v=vs.85).aspx
    "vk01":             Typeable(code=0x01, name='vk01'),
    "vk02":             Typeable(code=0x02, name='vk02'),
    "vk03":             Typeable(code=0x03, name='vk03'),
    "vk04":             Typeable(code=0x04, name='vk04'),
    "vk05":             Typeable(code=0x05, name='vk05'),
    "vk06":             Typeable(code=0x06, name='vk06'),
    "vk07":             Typeable(code=0x07, name='vk07'),
    "vk08":             Typeable(code=0x08, name='vk08'),
    "vk09":             Typeable(code=0x09, name='vk09'),
    "vk0A":             Typeable(code=0x0A, name='vk0A'),
    "vk0C":             Typeable(code=0x0C, name='vk0C'),
    "vk0D":             Typeable(code=0x0D, name='vk0D'),
    "vk0E":             Typeable(code=0x0E, name='vk0E'),
    "vk10":             Typeable(code=0x10, name='vk10'),
    "vk11":             Typeable(code=0x11, name='vk11'),
    "vk12":             Typeable(code=0x12, name='vk12'),
    "vk13":             Typeable(code=0x13, name='vk13'),
    "vk14":             Typeable(code=0x14, name='vk14'),
    "vk15":             Typeable(code=0x15, name='vk15'),
    "vk16":             Typeable(code=0x16, name='vk16'),
    "vk17":             Typeable(code=0x17, name='vk17'),
    "vk18":             Typeable(code=0x18, name='vk18'),
    "vk19":             Typeable(code=0x19, name='vk19'),
    "vk1A":             Typeable(code=0x1A, name='vk1A'),
    "vk1B":             Typeable(code=0x1B, name='vk1B'),
    "vk1C":             Typeable(code=0x1C, name='vk1C'),
    "vk1D":             Typeable(code=0x1D, name='vk1D'),
    "vk1E":             Typeable(code=0x1E, name='vk1E'),
    "vk1F":             Typeable(code=0x1F, name='vk1F'),
    "vk20":             Typeable(code=0x20, name='vk20'),
    "vk21":             Typeable(code=0x21, name='vk21'),
    "vk22":             Typeable(code=0x22, name='vk22'),
    "vk23":             Typeable(code=0x23, name='vk23'),
    "vk24":             Typeable(code=0x24, name='vk24'),
    "vk25":             Typeable(code=0x25, name='vk25'),
    "vk26":             Typeable(code=0x26, name='vk26'),
    "vk27":             Typeable(code=0x27, name='vk27'),
    "vk28":             Typeable(code=0x28, name='vk28'),
    "vk29":             Typeable(code=0x29, name='vk29'),
    "vk2A":             Typeable(code=0x2A, name='vk2A'),
    "vk2B":             Typeable(code=0x2B, name='vk2B'),
    "vk2C":             Typeable(code=0x2C, name='vk2C'),
    "vk2D":             Typeable(code=0x2D, name='vk2D'),
    "vk2E":             Typeable(code=0x2E, name='vk2E'),
    "vk2F":             Typeable(code=0x2F, name='vk2F'),
    "vk30":             Typeable(code=0x30, name='vk30'),
    "vk31":             Typeable(code=0x31, name='vk31'),
    "vk32":             Typeable(code=0x32, name='vk32'),
    "vk33":             Typeable(code=0x33, name='vk33'),
    "vk34":             Typeable(code=0x34, name='vk34'),
    "vk35":             Typeable(code=0x35, name='vk35'),
    "vk36":             Typeable(code=0x36, name='vk36'),
    "vk37":             Typeable(code=0x37, name='vk37'),
    "vk38":             Typeable(code=0x38, name='vk38'),
    "vk39":             Typeable(code=0x39, name='vk39'),
    "vk3A":             Typeable(code=0x3A, name='vk3A'),
    "vk41":             Typeable(code=0x41, name='vk41'),
    "vk42":             Typeable(code=0x42, name='vk42'),
    "vk43":             Typeable(code=0x43, name='vk43'),
    "vk44":             Typeable(code=0x44, name='vk44'),
    "vk45":             Typeable(code=0x45, name='vk45'),
    "vk46":             Typeable(code=0x46, name='vk46'),
    "vk47":             Typeable(code=0x47, name='vk47'),
    "vk48":             Typeable(code=0x48, name='vk48'),
    "vk49":             Typeable(code=0x49, name='vk49'),
    "vk4A":             Typeable(code=0x4A, name='vk4A'),
    "vk4B":             Typeable(code=0x4B, name='vk4B'),
    "vk4C":             Typeable(code=0x4C, name='vk4C'),
    "vk4D":             Typeable(code=0x4D, name='vk4D'),
    "vk4E":             Typeable(code=0x4E, name='vk4E'),
    "vk4F":             Typeable(code=0x4F, name='vk4F'),
    "vk50":             Typeable(code=0x50, name='vk50'),
    "vk51":             Typeable(code=0x51, name='vk51'),
    "vk52":             Typeable(code=0x52, name='vk52'),
    "vk53":             Typeable(code=0x53, name='vk53'),
    "vk54":             Typeable(code=0x54, name='vk54'),
    "vk55":             Typeable(code=0x55, name='vk55'),
    "vk56":             Typeable(code=0x56, name='vk56'),
    "vk57":             Typeable(code=0x57, name='vk57'),
    "vk58":             Typeable(code=0x58, name='vk58'),
    "vk59":             Typeable(code=0x59, name='vk59'),
    "vk5A":             Typeable(code=0x5A, name='vk5A'),
    "vk5B":             Typeable(code=0x5B, name='vk5B'),
    "vk5C":             Typeable(code=0x5C, name='vk5C'),
    "vk5D":             Typeable(code=0x5D, name='vk5D'),
    "vk5E":             Typeable(code=0x5E, name='vk5E'),
    "vk5F":             Typeable(code=0x5F, name='vk5F'),
    "vk60":             Typeable(code=0x60, name='vk60'),
    "vk61":             Typeable(code=0x61, name='vk61'),
    "vk62":             Typeable(code=0x62, name='vk62'),
    "vk63":             Typeable(code=0x63, name='vk63'),
    "vk64":             Typeable(code=0x64, name='vk64'),
    "vk65":             Typeable(code=0x65, name='vk65'),
    "vk66":             Typeable(code=0x66, name='vk66'),
    "vk67":             Typeable(code=0x67, name='vk67'),
    "vk68":             Typeable(code=0x68, name='vk68'),
    "vk69":             Typeable(code=0x69, name='vk69'),
    "vk6A":             Typeable(code=0x6A, name='vk6A'),
    "vk6B":             Typeable(code=0x6B, name='vk6B'),
    "vk6C":             Typeable(code=0x6C, name='vk6C'),
    "vk6D":             Typeable(code=0x6D, name='vk6D'),
    "vk6E":             Typeable(code=0x6E, name='vk6E'),
    "vk6F":             Typeable(code=0x6F, name='vk6F'),
    "vk70":             Typeable(code=0x70, name='vk70'),
    "vk71":             Typeable(code=0x71, name='vk71'),
    "vk72":             Typeable(code=0x72, name='vk72'),
    "vk73":             Typeable(code=0x73, name='vk73'),
    "vk74":             Typeable(code=0x74, name='vk74'),
    "vk75":             Typeable(code=0x75, name='vk75'),
    "vk76":             Typeable(code=0x76, name='vk76'),
    "vk77":             Typeable(code=0x77, name='vk77'),
    "vk78":             Typeable(code=0x78, name='vk78'),
    "vk79":             Typeable(code=0x79, name='vk79'),
    "vk7A":             Typeable(code=0x7A, name='vk7A'),
    "vk7B":             Typeable(code=0x7B, name='vk7B'),
    "vk7C":             Typeable(code=0x7C, name='vk7C'),
    "vk7D":             Typeable(code=0x7D, name='vk7D'),
    "vk7E":             Typeable(code=0x7E, name='vk7E'),
    "vk7F":             Typeable(code=0x7F, name='vk7F'),
    "vk80":             Typeable(code=0x80, name='vk80'),
    "vk81":             Typeable(code=0x81, name='vk81'),
    "vk82":             Typeable(code=0x82, name='vk82'),
    "vk83":             Typeable(code=0x83, name='vk83'),
    "vk84":             Typeable(code=0x84, name='vk84'),
    "vk85":             Typeable(code=0x85, name='vk85'),
    "vk86":             Typeable(code=0x86, name='vk86'),
    "vk87":             Typeable(code=0x87, name='vk87'),
    "vk88":             Typeable(code=0x88, name='vk88'),
    "vk90":             Typeable(code=0x90, name='vk90'),
    "vk91":             Typeable(code=0x91, name='vk91'),
    "vk92":             Typeable(code=0x92, name='vk92'),
    "vk97":             Typeable(code=0x97, name='vk97'),
    "vkA0":             Typeable(code=0xA0, name='vkA0'),
    "vkA1":             Typeable(code=0xA1, name='vkA1'),
    "vkA2":             Typeable(code=0xA2, name='vkA2'),
    "vkA3":             Typeable(code=0xA3, name='vkA3'),
    "vkA4":             Typeable(code=0xA4, name='vkA4'),
    "vkA5":             Typeable(code=0xA5, name='vkA5'),
    "vkA6":             Typeable(code=0xA6, name='vkA6'),
    "vkA7":             Typeable(code=0xA7, name='vkA7'),
    "vkA8":             Typeable(code=0xA8, name='vkA8'),
    "vkA9":             Typeable(code=0xA9, name='vkA9'),
    "vkAA":             Typeable(code=0xAA, name='vkAA'),
    "vkAB":             Typeable(code=0xAB, name='vkAB'),
    "vkAC":             Typeable(code=0xAC, name='vkAC'),
    "vkAD":             Typeable(code=0xAD, name='vkAD'),
    "vkAE":             Typeable(code=0xAE, name='vkAE'),
    "vkAF":             Typeable(code=0xAF, name='vkAF'),
    "vkB0":             Typeable(code=0xB0, name='vkB0'),
    "vkB1":             Typeable(code=0xB1, name='vkB1'),
    "vkB2":             Typeable(code=0xB2, name='vkB2'),
    "vkB3":             Typeable(code=0xB3, name='vkB3'),
    "vkB4":             Typeable(code=0xB4, name='vkB4'),
    "vkB5":             Typeable(code=0xB5, name='vkB5'),
    "vkB6":             Typeable(code=0xB6, name='vkB6'),
    "vkB7":             Typeable(code=0xB7, name='vkB7'),
    "vkB8":             Typeable(code=0xB8, name='vkB8'),
    "vkBA":             Typeable(code=0xBA, name='vkBA'),
    "vkBB":             Typeable(code=0xBB, name='vkBB'),
    "vkBC":             Typeable(code=0xBC, name='vkBC'),
    "vkBD":             Typeable(code=0xBD, name='vkBD'),
    "vkBE":             Typeable(code=0xBE, name='vkBE'),
    "vkBF":             Typeable(code=0xBF, name='vkBF'),
    "vkC0":             Typeable(code=0xC0, name='vkC0'),
    "vkC1":             Typeable(code=0xC1, name='vkC1'),
    "vkD8":             Typeable(code=0xD8, name='vkD8'),
    "vkDB":             Typeable(code=0xDB, name='vkDB'),
    "vkDC":             Typeable(code=0xDC, name='vkDC'),
    "vkDD":             Typeable(code=0xDD, name='vkDD'),
    "vkDE":             Typeable(code=0xDE, name='vkDE'),
    "vkDF":             Typeable(code=0xDF, name='vkDF'),
    "vkE0":             Typeable(code=0xE0, name='vkE0'),
    "vkE1":             Typeable(code=0xE1, name='vkE1'),
    "vkE2":             Typeable(code=0xE2, name='vkE2'),
    "vkE3":             Typeable(code=0xE3, name='vkE3'),
    "vkE5":             Typeable(code=0xE5, name='vkE5'),
    "vkE6":             Typeable(code=0xE6, name='vkE6'),
    "vkE7":             Typeable(code=0xE7, name='vkE7'),
    "vkE8":             Typeable(code=0xE8, name='vkE8'),
    "vkE9":             Typeable(code=0xE9, name='vkE9'),
    "vkF6":             Typeable(code=0xF6, name='vkF6'),
    "vkF7":             Typeable(code=0xF7, name='vkF7'),
    "vkF8":             Typeable(code=0xF8, name='vkF8'),
    "vkF9":             Typeable(code=0xF9, name='vkF9'),
    "vkFA":             Typeable(code=0xFA, name='vkFA'),
    "vkFB":             Typeable(code=0xFB, name='vkFB'),
    "vkFC":             Typeable(code=0xFC, name='vkFC'),
    "vkFD":             Typeable(code=0xFD, name='vkFD'),
    "vkFE":             Typeable(code=0xFE, name='vkFE'),
    }
